config/urls.py
from django.contrib import admin
from django.urls import path, include

from tester_app.views import MainView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainView.as_view(), name='main'),
    path('questions/', include('tester_app.urls', namespace='tester_app')),
]

tester_app/urls.py
from django.urls import path
from tester_app.apps import TesterAppConfig
from tester_app.views import QuestionListView, QuestionDetailView

app_name = TesterAppConfig.name


urlpatterns = [
    path('list/', QuestionListView.as_view(), name='question_list'),
    path('detail/<int:pk>', QuestionDetailView.as_view(), name='question_detail')
]

tester_app/models.py
from django.db import models


class Question(models.Model):
    """
    Модель вопроса, включающая в себя текст вопроса, ответа и категорию
    """
    question = models.TextField(max_length=200, unique=True, verbose_name='question_text')
    answer = models.TextField(verbose_name='text')
    category = models.CharField(max_length=200, verbose_name='category_name')

    def __str__(self):
        return self.question

    class Meta:
        verbose_name = 'Question'
        verbose_name_plural = 'Questions'

tester_app/views.py
from django.views.generic import DetailView, ListView, CreateView
from tester_app.models import Question


class MainView(ListView):
    model = Question
    template_name = 'tester_app/main.html'


class QuestionListView(ListView):
    model = Question
    template_name = 'tester_app/question_list.html'


class QuestionDetailView(DetailView):
    model = Question
    template_name = 'tester_app/question_detail.html'

tester_app/templates/tester_app/base.html
<load static>
    <!doctype html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Theory of Programming</title>
        <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <h5 class="my-0 mr-md-auto font-weight-normal">ToP</h5>
        <nav class="ms-auto justify-content-end">
            <a class="p-2 btn btn-outline-primary" href="#">Test yourself</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'tester_app:question_list' %}">All Questions</a>
            <a class="p-2 btn btn-outline-primary" href="#">New Question</a>
        </nav>
    </div>

    {% block content %}
    {% endblock %}

    <div class="container">
        <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
                <div class="col-12 col-md">
                    Theory of Programming
                    <small class="d-block mb-3 text-muted">&copy; 2077</small>
                </div>
                <div class="col-6 col-md">
                    <h5>Popular Themes</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Community</a></li>
                        <li><a class="text-muted" href="#">Community's opinion</a></li>
                        <li><a class="text-muted" href="#">Society's opinion</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>Additional</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="https://easyoffer.ru/">Easyoffer</a></li>
                        <li><a class="text-muted" href="https://www.youtube.com/">YouTube</a></li>
                        <li><a class="text-muted" href="https://translate.google.ru/">Google translate</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>About us</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Junior Python Developer</a></li>
                    </ul>
                </div>
            </div>
        </footer>
    </div>

    <script src="/static/js/bootstrap.bundle.min.js"></script>
    </body>
    </html>
</load>

tester_app/templates/tester_app/main.html
{% extends 'tester_app/base.html' %}

{% block content %}
<div class="container mt-5 pt-5">
    <h1 style="color: blue; text-align: center;">THEORY OF PROGRAMMING</h1>


    <div class="col-md-6 mx-auto">
        <form action="">
            <div class="form-group">
                <label for="">Select Category</label>
                <select name="category" id="" class="form-control">
                    <option value="Choose">Choose</option>
                    {% for category in catgories %}
                    <option value="{{category.name}}">{{category.name}}</option>
                    {% endfor %}
                </select>
            </div>
            <button class="btn btn-outline-primary mt-3">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

tester_app/templates/tester_app/question_detail.html
{% extends 'tester_app/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row text-center">
        <p>
        <h4 class="my-0 font-weight-normal">{{ question.text }}</h4>
        <p>
        <p>
            {{ question.category }}
        </p>
        <p>
            {% for answer in question.question_answer.all %}
                {{ answer }} <p>
            {% endfor %}
        </p>
    </div>
</div>

{% endblock %}

tester_app/templates/tester_app/question_list.html
{% extends 'tester_app/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <p class="lead">Question List</p>
</div>

<div class="row text-center">

    {% for question in question_list %}

    <div class="col-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ question.text }}</h4>
            </div>
            <div class="card-body">
                <a href="{% url 'tester_app:question_detail' question.pk %}"
                   class="w-50 btn btn-lg btn-outline-primary">Read</a><p></p>
                <a href="#"
                   class="w-50 btn btn-lg btn-outline-primary">Edit</a><p></p>
                <a href="#"
                   class="w-50 btn btn-lg btn-outline-warning">Delete</a>
            </div>
        </div>
    </div>

    {% endfor %}

</div>

{% endblock %}